services:
  backend:
    container_name: asos-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      PORT: 3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db

  db:
    container_name: postgres-db-dev
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: