export const DATABASE_TYPE = 'postgres';
export const DATA_SOURCE = 'DATA_SOURCE';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const HELLOWORLD_REPOSITORY = 'HELLOWORLD_REPOSITORY';
export const TAG_REPOSITORY = 'TAG_REPOSITORY';
export const USER_GROUP_REPOSITORY = 'USER_GROUP_REPOSITORY';
export const ENTRY_REPOSITORY = 'ENTRY_REPOSITORY';
